version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    hostname: mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=6Eu*76YTU!23uei
      - MYSQL_USER=root
      - MYSQL_PASSWORD=6Eu*76YTU!23uei
    ports:
      - "3306:3306"
    volumes:
      - ./src/mysql/my.cnf:/etc/mysql/mysql.conf.d:ro
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
      - ./databaseBackup/mysql:/var/backups/mysql:rw
    restart: always

  prove:
    container_name: prove
    build:
      context: ./src/PHP
      dockerfile: docker/Dockerfile
    hostname: prove
    ports:
      - "50080:80"
    volumes:
    #   - ./configure.conf:/etc/temphawk/configure.conf:ro
      # - ./src/PHP/docker/php7.2/php.ini:/etc/php/7.2/apache2/php.ini:ro
      # - ./src/PHP/docker/docker-entrypoint.sh:/entrypoint.sh:ro
      - ./src/PHP:/var/www/html/Prove:rw
      # - ./log/PHP:/var/log/PHP
      # - ./log/PHP/log:/var/www/html/PHP/storage/logs
    restart: always
    stdin_open: true
    tty: true
    entrypoint: /bin/sh

